### ISSUE TITLE
AMITT and DiSARM - MISP Galaxy format 

### ISSUE THREAD

**Issue by adulau** [DISARMFoundation/DISARMframeworks#22]
We have a complete MISP galaxy with [AMITT](https://github.com/MISP/misp-galaxy/blob/main/clusters/misinfosec-amitt-misinformation-pattern.json) which is significantly used by many MISP users.

We looked into the STIX format export but it seems kind of abuse of the MITRE ATT&CK patterns.  As we would like to go for a new galaxy for DiSARM, we would like to be sure that [XLS file](https://github.com/DISARMFoundation/DISARMframeworks/blob/main/DISARM_MASTER_DATA/DISARM_FRAMEWORKS_MASTER.xlsx) will remain the stable source. 

Thanks a lot for your work! 

@VVX7 what do you think about it?

**Comment by VVX7** [comment]
Hey @adulau !

That XLS file will remain the source. It's under active development as folks add/update new TTPs, but the document format shouldn't change. We'd love to see a new galaxy in MISP for DISARM.

**Comment by cvandeplas** [comment]
Hello @VVX7  and @adulau , 
I had a look today and the nice `generate_DISARM_pages` library made it quite easy. Thanks for delivering such a nice lib!

The current `generate_DISARM_MISP_galaxy.py` script currently only generates the techniques. Not yet the other components which could also be useful. (in separate galaxies/clusters)

Here is what it looks like in the MISP webui:
![Screenshot from 2023-12-02 17-56-31](https://github.com/DISARMFoundation/DISARMframeworks/assets/1073662/874b9b26-aeea-4da8-a47b-b74b1d5b5d46)

**Comment by cvandeplas** [comment]
In #23 many more objects are now generated.
